version: '3.9'

services:

  searcher:
    image: sting-searcher
    build:
      context: ./
      dockerfile: searcher.Dockerfile
      args:
        SGX: $SGX
        RA_TYPE: $RA_TYPE  
    devices:
      - /dev/isgx
    environment:
      RA_TLS_EPID_API_KEY: ${RA_TLS_EPID_API_KEY}
      RA_CLIENT_SPID: ${RA_CLIENT_SPID}
      SGX: ${SGX}
      DEBUG: ${DEBUG}
      ETH_SIGNER_KEY: "0x2e0834786285daccd064ca17f1654f67b4aef298acbb82cef9ec422fb4975622"
    volumes:
      - ./chain/keystores:/Sting-Flashbots/keystores
      # - ./chain/keystores:/Sting-Flashbots/searcher/input_data/keystores
      - ./searcher/src:/Sting-Flashbots/searcher/src/
      - shared:/shared
    working_dir: /Sting-Flashbots/searcher/src
    command: python simple.py


  builder:
    image: ghcr.io/initc3/flashbots-builder:481f1c3c2
    #build:
    #  context: ./
    #  dockerfile: geth.Dockerfile
    #  args:
    #    GETH_COMMIT: 481f1c3c23b51aa39822b3ba40cfafc653a451b8
    entrypoint: geth
    command:
      - --http
      - --http.api=engine,eth,web3,net,debug,flashbots
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/etc/jwt.hex
      - --datadir=/data  
      - --allow-insecure-unlock
      - --unlock=0x123463a4B065722E99115D6c222f267d9cABb524
      - --keystore=/etc/keystore
      - --password=/etc/geth_password.txt
      - --nodiscover
      - --syncmode=full
      - --verbosity=4
      - --mine
      - --builder
      - --builder.local_relay=true
      - --builder.secret_key=0x2e0834786285daccd064ca17f1654f67b4aef298acbb82cef9ec422fb4975622
      - --builder.relay_secret_key=0x2e0834786285daccd064ca17f1654f67b4aef298acbb82cef9ec422fb4975622
      - --builder.genesis_validators_root=0x83431ec7fcf92cfc44947fc0418e831c25e1d0806590231c439830db7ad54fda
      - --builder.genesis_fork_version=0x20000089
      - --builder.bellatrix_fork_version=0x20000091
      - --builder.beacon_endpoints=http://beacon-chain:3500
      - --miner.algotype=greedy
      - --miner.etherbase=0x123463a4B065722E99115D6c222f267d9cABb524
    ports:
      - 28545:28545
      - 8551:8551
      - 8545:8545
    depends_on:
      geth-genesis:
        condition: service_completed_successfully
    environment:
      SS_DIR: "/shared/"
      SS_ADDRESS: "0x4588765017b315E1d190f46B8f1911F49D918bc4"
      BUILDER_TX_SIGNING_KEY: "0x2e0834786285daccd064ca17f1654f67b4aef298acbb82cef9ec422fb4975622"
    volumes:
      - ./chain/execution/keystore/:/etc/keystore
      - ./chain/execution/geth_password.txt:/etc/geth_password.txt
      - ./chain/execution/jwtsecret:/etc/jwt.hex
      - genesis:/etc/genesis/
      - shared:/shared
      - data:/data
      # - ./chain/consensus/data:/data
      # - ./go-ethereum/cmd/geth:/geth-sgx/go-ethereum/cmd/geth

#configration based on https://github.com/avalonche/eth-pos-devnet/blob/master/docker-compose.yml
  geth-genesis:
    image: "ethereum/client-go:v1.11.6"
    command: --datadir=/data init /genesis/genesis.json
    depends_on:
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    volumes:
      - genesis:/genesis
      # - ./chain/execution/genesis.json:/genesis/genesis.json
      - data:/data

  create-beacon-chain-genesis:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:HEAD-5b8084"
    command:
      - testnet
      - generate-genesis
      - --fork=bellatrix
      - --num-validators=64
      - --output-ssz=/genesis/genesis.ssz
      - --chain-config-file=/consensus/config.yml
      - --geth-genesis-json-in=/execution/genesis.json
      - --geth-genesis-json-out=/genesis/genesis.json
    volumes:
      - ./chain/consensus/config.yml:/consensus/config.yml
      - ./chain/execution/genesis.json:/execution/genesis.json
      # - ./chain/execution/:/execution/
      - genesis:/genesis/

  beacon-chain:
    image: ghcr.io/initc3/flashbots-prysm:cecd2d9cb
    #build:
    #  context: ./
    #  dockerfile: beacon.Dockerfile
    #  args:
    #    COMMIT: cecd2d9cbb9bd32187dcdc8167fe72b77d48eebe
    command:
      - --datadir=/beacondata
      # No peers to sync with in this testnet, so setting to 0
      - --min-sync-peers=0
      - --genesis-state=/genesis/genesis.ssz
      - --interop-eth1data-votes
      - --bootstrap-node=
      # The chain configuration file used for setting up Prysm
      - --chain-config-file=/consensus/config.yml
      # We specify the chain id used by our execution client
      - --chain-id=32382
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=http://builder:8551
      - --accept-terms-of-use
      - --jwt-secret=/execution/jwtsecret
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
      - --http-mev-relay=http://builder:28545
    depends_on:
      builder:
        condition: service_started
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    ports:
      - 4000:4000
      - 3500:3500
      - 8080:8080
    volumes:
      - ./chain/consensus/config.yml:/consensus/config.yml
      - ./chain/execution/jwtsecret:/execution/jwtsecret
      - genesis:/genesis/
      # - ./chain/execution/genesis.json:/execution/genesis.json
      # - ./chain/consensus/beacondata:/beacondata

  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:HEAD-e4e8a0"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/validatordata
      - --accept-terms-of-use
      - --interop-num-validators=64
      - --interop-start-index=0
      - --chain-config-file=/consensus/config.yml
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
      - --enable-builder
    depends_on:
      beacon-chain:
        condition: service_started
    volumes:
      - ./chain/consensus/config.yml:/consensus/config.yml
      # - ./chain/consensus/validatordata:/validatordata

volumes:
  genesis:
  data:
  shared:
