version: '3.3'

services:

  # searcher:
  #   image: sting-searcher
  #   build:
  #     context: ./
  #     dockerfile: searcher.Dockerfile
  #     args:
  #       RA_CLIENT_SPID: $RA_CLIENT_SPID
  #       RA_CLIENT_LINKABLE: $RA_CLIENT_LINKABLE
  #       SGX: $SGX
  #       RA_TYPE: $RA_TYPE
  #   devices:
  #     - /dev/isgx
  #   # depends_on:
  #   #   validator:
  #   #     condition: service_started
  #   environment:
  #     RA_TLS_EPID_API_KEY: ${RA_TLS_EPID_API_KEY}
  #     RA_CLIENT_SPID: ${RA_CLIENT_SPID}
  #     SGX: ${SGX}
  #     DEBUG: ${DEBUG}
  #     ETH_SIGNER_KEY: "0x2e0834786285daccd064ca17f1654f67b4aef298acbb82cef9ec422fb4975622"
  #   working_dir: /Sting-Flashbots
  #   volumes:
  #     - aesmd-socket:/var/run/aesmd
  #   command: python send_bundle.py

  builder:
    image: geth-sgx-gramine
    build:
      context: ./
      dockerfile: builder.Dockerfile
      args:
        RA_CLIENT_SPID: $RA_CLIENT_SPID
        RA_CLIENT_LINKABLE: $RA_CLIENT_LINKABLE
        SGX: $SGX
        RA_TYPE: $RA_TYPE
    depends_on:
      aesmd:
        condition: service_started
      geth-genesis:
        condition: service_completed_successfully
    cap_add:
      - NET_ADMIN
    ports:
      - 28545:28545
      - 8551:8551
      - 8545:8545
    devices:
      - /dev/isgx
    security_opt:
      - seccomp:unconfined
    environment:
      RA_TLS_EPID_API_KEY: ${RA_TLS_EPID_API_KEY}
      RA_CLIENT_SPID: ${RA_CLIENT_SPID}
      RA_TYPE: ${RA_TYPE}
      SGX: ${SGX}
      DEBUG: ${DEBUG}
      BUILDER_TX_SIGNING_KEY: "0x2e0834786285daccd064ca17f1654f67b4aef298acbb82cef9ec422fb4975622"
    working_dir: /geth-sgx
    volumes:
      - aesmd-socket:/var/run/aesmd
      - ./chain/execution/keystore/:/etc/keystore
      - ./chain/execution/geth_password.txt:/etc/geth_password.txt
      - ./chain/execution/jwtsecret:/etc/jwt.hex
      - ./chain/execution/genesis.json:/etc/genesis/genesis.json
      - data:/data
      - cert:/cert
      # - ./chain/consensus/data:/data
      # - ./go-ethereum/cmd/geth:/geth-sgx/go-ethereum/cmd/geth

  aesmd:
    image: initc3/linux-sgx:2.19
    devices:
      - /dev/isgx
    volumes:
      - aesmd-socket:/var/run/aesmd
    user: aesmd
    working_dir: /opt/intel/sgx-aesm-service/aesm
    environment:
      LD_LIBRARY_PATH: /opt/intel/sgx-aesm-service/aesm
    command: ./aesm_service --no-daemon

#configration based on https://github.com/avalonche/eth-pos-devnet/blob/master/docker-compose.yml
  geth-genesis:
    image: "ethereum/client-go:latest"
    command: --datadir=/data init /execution/genesis.json
    volumes:
      - ./chain/execution/genesis.json:/execution/genesis.json
      - genesis:/genesis
      - data:/data

  create-beacon-chain-genesis:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest"
    command:
      - testnet
      - generate-genesis
      - --num-validators=64
      - --output-ssz=/genesis/genesis.ssz
      - --chain-config-file=/consensus/config.yml
    volumes:
      - ./chain/consensus:/consensus/
      - genesis:/genesis/

  beacon-chain:
    image: "eth-pos-devnet_beacon-chain:latest"
    command:
      - --datadir=/beacondata
      # No peers to sync with in this testnet, so setting to 0
      - --min-sync-peers=0
      - --genesis-state=/genesis/genesis.ssz
      - --interop-eth1data-votes
      - --bootstrap-node=
      # The chain configuration file used for setting up Prysm
      - --chain-config-file=/consensus/config.yml
      # We specify the chain id used by our execution client
      - --chain-id=32382
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=http://builder:8551
      - --chain-id=32382
      - --accept-terms-of-use
      - --jwt-secret=/execution/jwtsecret
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
      - --http-mev-relay=http://builder:28545
    depends_on:
      builder:
        condition: service_started
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    ports:
      - 4000:4000
      - 3500:3500
      - 8080:8080
    volumes:
      - ./chain/consensus:/consensus
      - ./chain/execution/jwtsecret:/execution/jwtsecret
      - genesis:/genesis/
      # - ./chain/consensus/beacondata:/beacondata

  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/validatordata
      - --accept-terms-of-use
      - --interop-num-validators=64
      - --interop-start-index=0
      - --chain-config-file=/consensus/config.yml
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
      - --enable-builder
    depends_on:
      beacon-chain:
        condition: service_started
    volumes:
      - ./chain/consensus:/consensus
      # - ./chain/consensus/validatordata:/validatordata

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
  genesis:
  data:
  cert: