version: '3.9'

services:
  # dev:
  #   image: sting
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   cap_add:
  #     - NET_ADMIN
  #   volumes:
  #     - ./:/Sting-Flashbots
  #   working_dir: /Sting-Flashbots
  #   platform: "linux/amd64"
  #   command: tail -F anything

  eth:
    image: sting-eth
    build:
      context: .
      dockerfile: eth.Dockerfile
    cap_add:
      - NET_ADMIN
    platform: "linux/amd64"
    volumes:
      - ./chain:/chain
    command: ["bash", "chain/chain.sh"]

  aesmd:
    image: initc3/linux-sgx:2.19
    devices:
      - /dev/isgx
    volumes:
      - aesmd-socket:/var/run/aesmd
    user: aesmd
    working_dir: /opt/intel/sgx-aesm-service/aesm
    environment:
      LD_LIBRARY_PATH: /opt/intel/sgx-aesm-service/aesm
    command: ./aesm_service --no-daemon


  builder:
    image: sting-gramine
    build:
      context: .
      dockerfile: gramine.Dockerfile
      args:
        RA_CLIENT_SPID: $RA_CLIENT_SPID
        SGX: 1
    depends_on:
      - aesmd
      - eth
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/isgx
    security_opt:
      - seccomp:unconfined
    environment:
      RA_TLS_EPID_API_KEY: ${RA_TLS_EPID_API_KEY}
      RA_CLIENT_SPID: ${RA_CLIENT_SPID}
      SGX: 1
      DEBUG: ${DEBUG}
    working_dir: /Sting-Flashbots/builder/src/
    volumes:
      - aesmd-socket:/var/run/aesmd
      - ./builder/src:/Sting-Flashbots/builder/src
      # - ./builder/input_data:/Sting-Flashbots/builder/input_data
      # - ./builder/enclave_data:/Sting-Flashbots/builder/enclave_data
      # - ./builder/output_data:/Sting-Flashbots/builder/output_data
      - shared:/shared_data
    command: sleep infinity

  relayer:
    image: sting-gramine
    build:
      context: .
      dockerfile: gramine.Dockerfile
      args:
        RA_CLIENT_SPID: $RA_CLIENT_SPID
        SGX: 1
    depends_on:
      - aesmd
      - eth
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/isgx
    security_opt:
      - seccomp:unconfined
    environment:
      RA_TLS_EPID_API_KEY: ${RA_TLS_EPID_API_KEY}
      RA_CLIENT_SPID: ${RA_CLIENT_SPID}
      SGX: 1
      DEBUG: ${DEBUG}
    working_dir: /Sting-Flashbots/relayer/src
    volumes:
      - aesmd-socket:/var/run/aesmd
      - ./relayer/src:/Sting-Flashbots/relayer/src
      # - ./relayer/input_data:/Sting-Flashbots/relayer/input_data
      # - ./relayer/enclave_data:/Sting-Flashbots/relayer/enclave_data
      # - ./relayer/output_data:/Sting-Flashbots/relayer/output_data
      - shared:/shared_data
    command: sleep infinity

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
  shared:

